name: TranslateThis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Composer Dependencies
              working-directory: ./app
              run: composer install --prefer-dist
            - name: Config phpunit Tests
              working-directory: ./app
              run: pwd && ls -la
            - name: Run Tests
              working-directory: ./app
              run: composer run-phpunit
            - run: docker build -t rasimaghayev/php-nginx:1.0 -f ./nginx/Dockerfile .
            - run: docker build --target app -t rasimaghayev/php-composer:1.2 -f ./php/Dockerfile .
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push rasimaghayev/php-composer:1.2
            - run: docker push rasimaghayev/php-nginx:1.0